import type { ErdColumn, ErdDiagram, ErdRelation, ErdTable } from './types'
import { commentText } from './comments'

const MARIADB_TABLE_OPTIONS = 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci'

/** MariaDB 식별자는 항상 백틱으로 감싸 예약어·한글·공백·특수문자가 있어도 안전하게 만든다. */
function quote(name: string): string {
  return `\`${(name || 'unnamed').replace(/`/g, '``')}\``
}

function quoteString(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "''")}'`
}

/** PostgreSQL 계열 타입이 남은 기존 ERD도 MariaDB에서 실행할 수 있는 타입으로 바꾼다. */
function mariaDbType(type: string): string {
  const raw = type.trim()
  if (!raw) return 'VARCHAR(255)'
  const upper = raw.toUpperCase()
  if (upper === 'SERIAL' || upper === 'SERIAL4') return 'INT AUTO_INCREMENT'
  if (upper === 'BIGSERIAL' || upper === 'SERIAL8') return 'BIGINT AUTO_INCREMENT'
  if (upper === 'BOOLEAN' || upper === 'BOOL') return 'TINYINT(1)'
  if (upper === 'UUID') return 'CHAR(36)'
  if (upper === 'JSONB') return 'JSON'
  if (upper === 'BYTEA') return 'LONGBLOB'
  if (upper === 'TIMESTAMPTZ' || upper === 'TIMESTAMP WITH TIME ZONE') return 'DATETIME'
  if (upper === 'DOUBLE PRECISION' || upper === 'REAL') return 'DOUBLE'
  if (upper === 'INT4' || upper === 'INTEGER') return 'INT'
  if (upper === 'INT8') return 'BIGINT'
  if (upper === 'VARCHAR') return 'VARCHAR(255)'
  if (upper === 'CHARACTER VARYING') return 'VARCHAR(255)'
  if (upper === 'CHARACTER') return 'CHAR(1)'
  return raw
}

function columnDdl(col: ErdColumn, indent = '  '): string {
  const parts: string[] = [quote(col.name), mariaDbType(col.type)]
  const comment = commentText(col)
  if (!col.nullable) parts.push('NOT NULL')
  if (col.unique && !col.isPK) parts.push('UNIQUE')
  if (col.defaultVal !== undefined && col.defaultVal !== '') parts.push(`DEFAULT ${col.defaultVal}`)
  else if (col.nullable) parts.push('DEFAULT NULL')
  if (comment) parts.push(`COMMENT ${quoteString(comment)}`)
  return indent + parts.join(' ')
}

function tableDdl(table: ErdTable): string {
  const tableName = quote(table.name || 't_unnamed')
  const cols = table.columns.map((column) => columnDdl(column))
  const primaryKeys = table.columns.filter((column) => column.isPK).map((column) => quote(column.name))
  const inside = [...cols]
  if (primaryKeys.length > 0) inside.push(`  PRIMARY KEY (${primaryKeys.join(', ')})`)
  const tableComment = commentText(table)
  const commentOption = tableComment ? ` COMMENT=${quoteString(tableComment)}` : ''
  return [
    `CREATE TABLE IF NOT EXISTS ${tableName} (`,
    inside.join(',\n'),
    `) ${MARIADB_TABLE_OPTIONS}${commentOption};`,
  ].join('\n')
}

function shortHash(value: string): string {
  let hash = 5381
  for (const char of value) hash = ((hash * 33) ^ char.charCodeAt(0)) >>> 0
  return hash.toString(36)
}

/** MariaDB 제약조건 이름은 64자 이하여야 하므로, 사람이 읽을 부분과 안정적인 해시를 결합한다. */
function foreignKeyName(relation: ErdRelation, fromTable: ErdTable, toTable: ErdTable, toColumn: ErdColumn): string {
  const source = `${toTable.name}_${toColumn.name}_${fromTable.name}`
  const readable = source.toLowerCase().replace(/[^a-z0-9_]+/g, '_').replace(/^_+|_+$/g, '') || 'relation'
  const suffix = shortHash(`${relation.id}:${source}`)
  return `fk_${readable.slice(0, 59 - suffix.length)}_${suffix}`
}

function relationDdl(relation: ErdRelation, tables: ErdTable[]): string | null {
  const parentTable = tables.find((table) => table.id === relation.fromTable)
  const childTable = tables.find((table) => table.id === relation.toTable)
  if (!parentTable || !childTable) return null
  const parentColumn = parentTable.columns.find((column) => column.id === relation.fromColumn)
  const childColumn = childTable.columns.find((column) => column.id === relation.toColumn)
  if (!parentColumn || !childColumn) return null

  return [
    `ALTER TABLE ${quote(childTable.name)}`,
    `  ADD CONSTRAINT ${quote(foreignKeyName(relation, parentTable, childTable, childColumn))}`,
    `  FOREIGN KEY (${quote(childColumn.name)}) REFERENCES ${quote(parentTable.name)} (${quote(parentColumn.name)});`,
  ].join('\n')
}

/**
 * ERD 다이어그램을 MariaDB DDL로 내보낸다.
 * 기본 엔진·문자셋·콜레이션은 InnoDB/utf8mb4/utf8mb4_general_ci로 고정한다.
 */
export function toSql(diagram: ErdDiagram, opts: { dropFirst?: boolean } = {}): string {
  const chunks: string[] = [
    `-- ${diagram.meta.title || 'ERD'} — MariaDB DDL`,
    '-- Generated by note ERD Designer',
    '',
  ]

  if (opts.dropFirst) {
    for (const table of [...diagram.tables].reverse()) chunks.push(`DROP TABLE IF EXISTS ${quote(table.name)};`)
    chunks.push('')
  }

  for (const table of diagram.tables) {
    chunks.push(tableDdl(table))
    chunks.push('')
  }

  const foreignKeys = diagram.relations
    .map((relation) => relationDdl(relation, diagram.tables))
    .filter((ddl): ddl is string => Boolean(ddl))
  if (foreignKeys.length > 0) {
    chunks.push('-- Foreign key constraints')
    chunks.push(foreignKeys.join('\n\n'))
  }

  return chunks.join('\n')
}
